#pragma once
void login_menu();
void user_menu();
void common_menu();
void attendance_menu();
void analytics();
void screen();
void step1();
void step_member();
void step_trainer();
void step_staff();
void step_equipment();
void step_package();
void step_attendance();
void add_att();
void view_att();
void search_att();
void update_att();
void remove_att();